# -*- coding: utf-8 -*-
"""Copy of ElasticNetOcean2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pUEgYvZEtBS4hb_oAQ9oEYIz9_deRiSW
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('/content/OceanFactors (4) - Copy of OceanFactors (4) (2).csv')

dataset.info()

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

X

y

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

X_train

X_test

y_train

y_test

from sklearn.linear_model import ElasticNet
enet_tuned = ElasticNet().fit(X_train,y_train)

# Let's now calculate the error for the test set using this final model.

y_pred = enet_tuned.predict(X_test)

from sklearn.metrics import mean_squared_error,r2_score
print('RMSE:',np.sqrt(mean_squared_error(y_test,y_pred)))
print('R2:',r2_score(y_test,y_pred))